### ISSUE TITLE
SteamID Format

### ISSUE THREAD

**Issue by Nexxed** [BuycraftPlugin/Tebex-SourceMod#3]
Some plugins do not support Steam64, which is the only SteamID format that is supported currently.
These same plugins rely on the regular/standard SteamID format, which isn't supported and will need updating to support Steam64.

While this is an issue for the server owners that use these plugins, I still believe that the SourceMod plugin should support `{steamid}` which would be in the following format: `STEAM_0:0:00000000`, `STEAM_0:1:00000000`, etc.

**Comment by crashzk** [comment]
Same problem here, I even contacted support to see this.

Currently for CSGO servers there is only the {username} variable option and from what I've tested using it there may be bugs.

In the case of removing when the product/service that the player bought expires, it removes by the username of the player on the web/site, but if the player changes nick and does not enter the site, it does not update, at least this occurs in my tests.

Solution, SteamID support for plugin instead of using SteamID64

Just for feedback, email I sent to support:
```
Currently the store for CSGO servers does not support SteamID, and the CSGO servers to give privileges to players the best way is by SteamID, this format, for example, STEAM_1:1:64012428.

I tried the variables:
- {id}
- {steamid}

And none of them work for CSGO, even using Tebex Plugin for CSGO.

In this case I managed to finish the sale of privileges and activation just using the {username} variable, problem that it uses the players username when logging into the store, and as my store removes the privileges after it expires to remove it uses the same username, however the player no longer logs in to the store and with that he can change his nick/username in the game so he doesn't remove the privileges.

Would it be possible to implement the {steamid} variable for the CSGO Plugin as well?
```

**Comment by crashzk** [comment]
I believe I would need to change **`AuthId_SteamID64`** to **`AuthId_Steam2`**.

https://github.com/tebexio/Tebex-SourceMod/blob/640b155e2cb18778650b9fc71811b04ed2883831/commands/forcecheck.sp#L64

https://sm.alliedmods.net/new-api/clients/AuthIdType

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to report this issue, I'm sorry it's been slow to get resolved — we're working on it!

Unfortunately, this issue is old enough that we've had to close it. But if you see any other issues (especially ones with the same or similar symptoms), please reply here and I'll look into getting them fixed.

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and we would love to know what issues still exist so they can be fixed for the new plugin.

Apologies for the issues you have faced!

**Comment by crashzk** [comment]
Yes, this problem still exists and the plugin needs to be rewritten for SourceMod 1.11 and 1.12
